### ISSUE TITLE
fix: Maximum 함수 버그 수정

### ISSUE THREAD

**Issue by lspc678** [OpenSourceProgramming/INHA_OSAP_004_Froyo#35]
# 👀 이슈 (issue)

Maximum() 함수에 버그가 발견되어 이를 수정하고자 합니다. 확인된 내용은 아래와 같습니다.
* depth가 잘못 출력되는 현상
* Set에 존재하지 않는 원소에 대해 Segmentation fault가 발생

첫 번째 이슈는 Find() 함수에 있는 parameter 값을 key 대신 해당 노드의 원소의 값으로 설정하면 될 것 같습니다. 그리고 두 번째 이슈는 Set에 존재하지 않는 원소라고 판단이 되면 곧바로 -1, -1을 출력하고 종료하면 될 것 같습니다.

![20231130 Maximum 함수 버그](https://github.com/OpenSourceProgramming/INHA_OSAP_004_Froyo/assets/79794123/71bcc715-29a7-4918-ab2e-7a7839626180)

# 🚀 to-do

- [x] depth가 잘못 출력되는 현상 수정
- [x] Set에 존재하지 않는 원소에 대해 Maximum() 함수를 호출했을 때 노드의 값과 depth 값이 각각 -1이 출력되도록 수정

**Comment by longcard** [comment]
Maximum() 함수와 Minimum() 함수의 코드가 동일하여 여기에 코멘트 드립니다.
1. 혹시 첫 번째 이슈는 find()함수를 수정해야 하는 것이기에 Maximum(), Minimum() 함수를 수정하지 않고 Find() 함수만 수정하면 되는 게 맞을까요?
2. Set에 존재하지 않는 원소에 대해 Segmentation fault가 발생하는 문제는 Maximum(), Minimum() 함수에서 수정을 해야하는 부분이 맞을까요?
제가 제대로 이해했는지 확인 차 코멘트 남깁니다.

프로젝트에서 큰 부분 담당해주셔서 항상 감사드립니다..

**Comment by lspc678** [comment]
> Maximum() 함수와 Minimum() 함수의 코드가 동일하여 여기에 코멘트 드립니다.
> 
> 1. 혹시 첫 번째 이슈는 find()함수를 수정해야 하는 것이기에 Maximum(), Minimum() 함수를 수정하지 않고 Find() 함수만 수정하면 되는 게 맞을까요?
> 2. Set에 존재하지 않는 원소에 대해 Segmentation fault가 발생하는 문제는 Maximum(), Minimum() 함수에서 수정을 해야하는 부분이 맞을까요?
>    제가 제대로 이해했는지 확인 차 코멘트 남깁니다.
> 
> 프로젝트에서 큰 부분 담당해주셔서 항상 감사드립니다..

1. 네 맞습니다. 정확히는 Find() 함수를 호출할 때 parameter를 잘못 설정해서 발생하는 문제로 보입니다.
2. 네 맞습니다.
